# Devcontainer Dockerfile

# Use the base image for Python 3.9 on Ubuntu 22.04
FROM mcr.microsoft.com/vscode/devcontainers/python:3.9-22.04

# Install PyTorch
RUN pip install torch torchvision torchaudio
